server:
  port: 8102
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: mcp-server-weixin
  main:
    banner-mode: off
    # stdio 模式打开，sse 模式，注释掉。
#    web-application-type: none
  ai:
    mcp:
      server:
        name: ${spring.application.name}
        version: 1.0.0

weixin:
  api:
    original_id: gh_9a5f9b51f4e0
    app-id: wxd791e178e4628317
    app-secret: c459c6bd2f7850c2e3e6416d5dde9275
    template_id: cVAmZs48H8pXGX7mzwaAXc9RCsTivllXLM6Js7V-0D4
    touser: ojiW43JYbdtwA6ogDuakrCWg2z_8

logging:
  # stdio 模式打开，sse 模式，注释掉。
#  pattern:
#    console:
  file:
    name: data/log/${spring.application.name}.log
